WIP Add guard to prevent ReferenceError when ActionCable is used in non-browser environments
Previously calling `require('actioncable')` in node would throw
```
ReferenceError: self is not defined
```
It could've been worked around by defining the `self` global before
requiring ActionCable, but that is a rather harsh requirement, and this
guard avoids the need for it.

WIPTODO:
- test it by importing the library in react native, then reword this
  commit message